# Object in Python

* Everything is an object
* We can create our own objects

In [111]:
from math import sqrt, atan2, cos, sin, pi
class Complex:
    def __init__(self, re_part, im_part):
        self.re = re_part
        self.im = im_part

    def conjugate(self):
        output = Complex(self.re, -self.im)
        return output

    def __str__(self):
        if self.im>=0:
            return '{re} + {im}J'.format(re=self.re, 
                                             im=self.im)
        else:
            return '{re} - {im}J'.format(re=self.re, 
                                             im=-self.im)
    def __repr__(self):
        return f'Complex({self.re}, {self.im})'
    
    def __eq__(self, other):
        if isinstance(other, (float, int)):
            return self.im==0 and self.re==other
        return self.re==other.re and self.im==other.im

    @staticmethod
    def _convert_to_complex(other):
        if isinstance(other, (float, int)):
            return Complex(other, 0)
        return other
        
    def __add__(self, other):
        other = self._convert_to_complex(other)
        if isinstance(other, Complex):
            return Complex(self.re + other.re, self.im + other.im)
        return NotImplemented
    
    def __sub__(self, other):
        other = self._convert_to_complex(other)
        if isinstance(other, Complex):
            return Complex(self.re - other.re, self.im - other.im)    
        return NotImplemented
    
    def __mul__(self, other):
        other = self._convert_to_complex(other)
        if isinstance(other, Complex):
            return Complex(self.re*other.re - self.im*other.im , 
                       self.im*other.re + self.re*other.im)   
        return NotImplemented

    def __truediv__(self, other):
        other = self._convert_to_complex(other)
        if isinstance(other, Complex):
            return from_polar(self.r/other.r, self.theta-other.theta)
        return NotImplemented
    
    def __rmul__(self, other):
        return self * other
    
    @property
    def r(self):
        return sqrt(self.re**2 + self.im**2)

    @property
    def theta(self):
        return atan2(self.im, self.re)

def from_polar(r, theta):
    return Complex(r*cos(theta), r*sin(theta))

class PureImaginary(Complex):
    def __init__(self, im):
        #self.im = im
        #self.re = 0
        Complex.__init__(self, 0, im)
    
    def __str__(self):
        return f'{self.im}J'

In [103]:
z = PureImaginary(4)
print(z)
isinstance(z, Complex)
z + 2

4J


Complex(2, 4)

In [98]:
z1 = Complex(1, 2)
z2 = Complex(3, 2)
z1/z2

Complex(0.5384615384615384, 0.30769230769230765)

In [97]:
from_polar(1, pi/4)

Complex(0.7071067811865476, 0.7071067811865475)

In [92]:
z1 = Complex(1, 2)

z1.r
z1.theta

1.1071487177940904

In [85]:
z1 = Complex(1, 2)
2*z1

Complex(2, 4)

In [86]:
z1 = Complex(1, 2)
z2 = Complex(3, 2)
z1+z2

Complex(4, 4)

In [74]:
z1 * z2

Complex(-1, 8)

In [56]:
z = Complex(1, 0)
1==z

True

In [48]:
z1 = Complex(1, 2)
z2 = Complex(1, 2)
z1==z2

True

In [42]:
z = Complex(1, 4)
isinstance(z, Complex)

True

In [43]:
z = Complex(1, 3)

z_conj = z.conjugate()
z_conj.imag

-3

In [44]:
print(z_conj)

1 - 3J


In [45]:
z_conj

Complex(1, -3)

In [39]:
import numpy as np
a = np.arange(5)
print(a)
a

[0 1 2 3 4]


array([0, 1, 2, 3, 4])

In [40]:
np.array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [110]:
class Test:
    b = 4
    def __init__(self, a):
        self.a = a
        
t = Test(3)
t.a
t.b
Test.b

Complex.__init__

<function __main__.Complex.__init__(self, re_part, im_part)>

In [132]:
def multiplication(a, b):
    out = a.__mul__(b)
    if out!=NotImplemented:
        return out
    out = b.__rmul__(a)
    if out!=NotImplemented:
        return out
    raise Exception('Cannot multipliy {} by {}'.format(type(a), type(b))
                   )
    

In [137]:
multiplication(z, z.conjugate())

Complex(10, 0)

### Special methods

* `__init__`
* `__repr__`, `__str__`


Unary and binary operator
* `__neg__`
* `__add__`, `__sub__`, `__mul__`, `__truediv__`, `__mod__`, `__pow__`
* `__radd__`, ...
* `__eq__` (==), `__ne__` (!=), `__lt__` (<), `__le__` (<=), `__gt__`, `__ge__`
* `__or__`, `__and__`, `__xor__`


Containers emulation
* a[key] => `a.__getitem__(key)`
* a[key] = val => `a.__setitem__(key, val)`
* del a[key] => `a.__delitem__(key)`
* len(a) => `a.__len__()`
* for elm in a => `for elm in a.__iter__()`

### Attributes and property
* Class attributes and object attributes
* property

### Heritage
* isinstance 

### Dataclasses
* Object with atributes set automatically in the ``__init__`` : https://docs.python.org/3/library/dataclasses.html

In [6]:
class Music:
    def __init__(self):
        self.durations = []
        self.frequencies = []
    
    def append(self, frequency, duration):
        self.durations.append(duration)
        self.frequencies.append(frequency)
        
    def __getitem__(self, key):
        return self.frequencies[key], self.durations[key]
    
    def __len__(self):
        return len(self.frequencies)

    def __iter__(self):
        return zip(self.frequencies, self.durations)
    
    def __call__(self, arg1):
        print('HELLO', arg1)

In [7]:
my_music = Music()
my_music.append(440, .5)
my_music.append(550, .5)

my_music[0]

for freq, dur in my_music:
    print(freq, dur)
    
my_music('poeipsipfoisdf')

440 0.5
550 0.5
HELLO poeipsipfoisdf


In [2]:
import dataclasses

@dataclasses.dataclass
class MyClass(object):
    a : int = 0
    b : float = 0.0

c = MyClass(b=3.14)


{'a': 0, 'b': 3.14}