# Numpy
## Examples
* Why numpy? data type

## Array creation 
* array :  partir d'une liste
* zeros, ones, eye
* arange
* linspace, logspace
* np.random.rand, ...

## Usefull functions
* ufunc / vectorize command
* methods/ numpy functions (max, min, mean, std, sort, ...)


In [6]:
import numpy as np

a = np.array([1, 2, 45, 567])

2*a

array([   2,    4,   90, 1134])

In [12]:
np.arange(1, 10, step=4)

array([1, 5, 9])

In [14]:
## WARNING 
np.linspace(start=0, stop=1, num=10, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [18]:
a = np.ones(14)

a[2] = 2.45
a

array([1.  , 1.  , 2.45, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  ])

In [4]:
from numpy import log

log(a)

array([0.        , 0.69314718, 3.80666249, 6.3403593 ])

In [19]:
np.logspace(0, 2, 20, endpoint=False)

array([ 1.        ,  1.25892541,  1.58489319,  1.99526231,  2.51188643,
        3.16227766,  3.98107171,  5.01187234,  6.30957344,  7.94328235,
       10.        , 12.58925412, 15.84893192, 19.95262315, 25.11886432,
       31.6227766 , 39.81071706, 50.11872336, 63.09573445, 79.43282347])

In [20]:
np.random.rand(10)

array([9.79007175e-04, 1.71743387e-01, 8.46981151e-01, 1.37741058e-01,
       9.82951493e-01, 4.96975880e-01, 5.29207959e-01, 1.69975646e-01,
       3.97522476e-01, 8.69965184e-01])

In [26]:
a = np.random.normal(loc=0, scale=4, size=1000000)

np.mean(a)

0.004288096639160935

In [31]:

def my_std(a):
    return np.sqrt(np.mean(a**2 - np.mean(a)**2))

my_std(a)

3.996079904249352

In [32]:
np.std(a)

3.9960799042493513

In [34]:
print(np.min(a))
np.argmin(a)

-20.134758526217613


876766

In [36]:
np.mean(np.cos(a))

-0.0002114538683574036

In [38]:
def lorentz(x):
    return 1/(1+x**2)

lorentz(1)
lorentz(np.linspace(-1, 1))

array([0.5       , 0.5208243 , 0.54247628, 0.56494118, 0.58819206,
       0.61218766, 0.63687003, 0.66216216, 0.68796562, 0.71415824,
       0.74059223, 0.76709265, 0.79345671, 0.81945392, 0.84482759,
       0.86929761, 0.89256506, 0.91431835, 0.93424125, 0.9520222 ,
       0.96736503, 0.98      , 0.98969497, 0.99626556, 0.99958368,
       0.99958368, 0.99626556, 0.98969497, 0.98      , 0.96736503,
       0.9520222 , 0.93424125, 0.91431835, 0.89256506, 0.86929761,
       0.84482759, 0.81945392, 0.79345671, 0.76709265, 0.74059223,
       0.71415824, 0.68796562, 0.66216216, 0.63687003, 0.61218766,
       0.58819206, 0.56494118, 0.54247628, 0.5208243 , 0.5       ])

In [41]:
def double(x):
    return 2*x

print(double(1))
print(double(np.linspace(-1, 1)))
print(double('Bonjour'))
print(double({'a':'hello'}))

2
[-2.         -1.91836735 -1.83673469 -1.75510204 -1.67346939 -1.59183673
 -1.51020408 -1.42857143 -1.34693878 -1.26530612 -1.18367347 -1.10204082
 -1.02040816 -0.93877551 -0.85714286 -0.7755102  -0.69387755 -0.6122449
 -0.53061224 -0.44897959 -0.36734694 -0.28571429 -0.20408163 -0.12244898
 -0.04081633  0.04081633  0.12244898  0.20408163  0.28571429  0.36734694
  0.44897959  0.53061224  0.6122449   0.69387755  0.7755102   0.85714286
  0.93877551  1.02040816  1.10204082  1.18367347  1.26530612  1.34693878
  1.42857143  1.51020408  1.59183673  1.67346939  1.75510204  1.83673469
  1.91836735  2.        ]
BonjourBonjour


TypeError: unsupported operand type(s) for *: 'int' and 'dict'

In [43]:
def gaussian(x):
    return np.exp(-x**2)

gaussian(np.linspace(-1, 1))

array([0.36787944, 0.39850576, 0.43024581, 0.46296872, 0.49652326,
       0.53073839, 0.56542417, 0.60037304, 0.63536159, 0.67015256,
       0.70449734, 0.73813873, 0.77081398, 0.80225813, 0.8322075 ,
       0.86040332, 0.88659543, 0.91054591, 0.93203274, 0.95085313,
       0.96682677, 0.97979867, 0.98964169, 0.99625858, 0.99958359,
       0.99958359, 0.99625858, 0.98964169, 0.97979867, 0.96682677,
       0.95085313, 0.93203274, 0.91054591, 0.88659543, 0.86040332,
       0.8322075 , 0.80225813, 0.77081398, 0.73813873, 0.70449734,
       0.67015256, 0.63536159, 0.60037304, 0.56542417, 0.53073839,
       0.49652326, 0.46296872, 0.43024581, 0.39850576, 0.36787944])

In [47]:
def my_abs(x):
    N = len(x)
    output = np.zeros(N)
    for i in range(N):
        if x[i]>=0:
            output[i] = x[i]
        else:
            output[i] = -x[i]
    return output
    
#my_abs(-3)

my_abs(np.linspace(-1, 1))

array([1.        , 0.95918367, 0.91836735, 0.87755102, 0.83673469,
       0.79591837, 0.75510204, 0.71428571, 0.67346939, 0.63265306,
       0.59183673, 0.55102041, 0.51020408, 0.46938776, 0.42857143,
       0.3877551 , 0.34693878, 0.30612245, 0.26530612, 0.2244898 ,
       0.18367347, 0.14285714, 0.10204082, 0.06122449, 0.02040816,
       0.02040816, 0.06122449, 0.10204082, 0.14285714, 0.18367347,
       0.2244898 , 0.26530612, 0.30612245, 0.34693878, 0.3877551 ,
       0.42857143, 0.46938776, 0.51020408, 0.55102041, 0.59183673,
       0.63265306, 0.67346939, 0.71428571, 0.75510204, 0.79591837,
       0.83673469, 0.87755102, 0.91836735, 0.95918367, 1.        ])

In [57]:
def my_abs(x):
    if x>=0:
        return x
    else:
        return -x

my_abs = np.vectorize(my_abs)
    
    
#def _my_vectorize(function):
#    def vec_function(x):
#        N = len(x)
#        output = np.zeros(x)
#        for i in range(N):
#            output[i] = function(x[i])
#        return output
#    return vec_function




In [58]:
x = np.random.normal(size=1000000)

In [59]:
%timeit y = my_abs(x)

118 ms ± 255 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
x = np.random.normal(size=10)
x

array([ 0.94495389, -0.80426581,  0.47857847, -0.467796  ,  0.5516559 ,
       -0.79695271, -0.92079193,  0.84902683, -0.67497844,  1.54126412])

In [66]:
x>=0

array([ True, False,  True, False,  True, False, False,  True, False,
        True])

In [68]:
x[x>=0] 

array([0.94495389, 0.47857847, 0.5516559 , 0.84902683, 1.54126412])

In [72]:
N = len(x)
output = np.zeros(N)

mask = (x>=0)
output[mask] = x[mask]
output[~mask] = -x[~mask]

output

def my_abs_mask(x):
    N = len(x)
    output = np.zeros(N)
    mask = (x>=0) # array of bool
    output[mask] = x[mask] # [elm for i, elm in enumerate(x) if mask[i] is True]
    output[~mask] = -x[~mask]
    return output

In [73]:
x = np.random.normal(size=1000000)

In [74]:
%timeit y = my_abs_mask(x)

20.9 ms ± 131 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [77]:
%timeit np.where(x<0, -x, x)

5.51 ms ± 70.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
#np.where(x<0, 1J*sqrt(-x), sqrt(x))

## Tableaux 2D (et nD)
* meshgrid, indices, fromfunction
* methodes/numpy functions
* linear algebra, matrices

In [78]:
l = [[1, 2, 4], [1, 5, 6]]
a = np.array(l)
a

array([[1, 2, 4],
       [1, 5, 6]])

In [81]:
a[(1, 2)]

6

In [83]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [85]:
a = np.random.normal(size=(3, 5))

In [87]:
np.sum(a)

0.9944131594552313

In [88]:
np.sum(a, axis=1)

array([ 0.94245494, -2.82092816,  2.87288637])

In [89]:
a

array([[-0.31551281,  1.36696878, -0.93579118,  0.10137912,  0.72541103],
       [-2.16095813, -0.72331822,  0.17651728, -1.14855164,  1.03538255],
       [ 0.67469412,  0.44723815,  0.82545447, -0.26551264,  1.19101227]])

In [91]:
a[1:3, 3:4]

array([[-1.14855164],
       [-0.26551264]])

In [92]:
a[:, 1]

array([ 1.36696878, -0.72331822,  0.44723815])

In [93]:
x = np.linspace(-1, 1, 4)
y = np.linspace(5, 6, 3)

np.meshgrid(x, y)

[array([[-1.        , -0.33333333,  0.33333333,  1.        ],
        [-1.        , -0.33333333,  0.33333333,  1.        ],
        [-1.        , -0.33333333,  0.33333333,  1.        ]]),
 array([[5. , 5. , 5. , 5. ],
        [5.5, 5.5, 5.5, 5.5],
        [6. , 6. , 6. , 6. ]])]

In [95]:
a = np.array([[1, 3, 4], [6, 6, 7]])
b = np.array([[4, 6, 0], [0, 1, 3]])

In [96]:
a

array([[1, 3, 4],
       [6, 6, 7]])

In [97]:
b

array([[4, 6, 0],
       [0, 1, 3]])

In [102]:
# Product item by item
a*b

array([[ 4, 18,  0],
       [ 0,  6, 21]])

In [103]:
# Matrix product
a@b.transpose()

array([[22, 15],
       [60, 27]])

In [104]:
a = np.random.normal(size=(4, 4))
a

array([[-0.36681465, -2.5173871 ,  0.4063379 , -1.18793459],
       [ 0.24808883, -0.90042249, -1.50692676,  0.43568086],
       [-0.01330466, -0.30401783,  0.82731958,  0.04194514],
       [-0.27499577, -1.26462343,  2.23438185, -0.69289188]])

In [107]:
np.linalg.inv(a)@a

array([[ 1.00000000e+00,  6.67994735e-15, -2.17244861e-14,
         1.02359570e-15],
       [ 8.01421133e-18,  1.00000000e+00, -2.91470892e-16,
         3.69313131e-17],
       [-5.27139953e-17, -3.02186476e-16,  1.00000000e+00,
        -5.70200166e-17],
       [-4.65877032e-17, -1.21203242e-15,  3.12475609e-15,
         1.00000000e+00]])

In [108]:
np.linalg.eig(a)

(array([-1.06505204+0.95914915j, -1.06505204-0.95914915j,
        -0.03943665+0.j        ,  1.03673129+0.j        ]),
 array([[ 0.83401018+0.j        ,  0.83401018-0.j        ,
         -0.94539192+0.j        ,  0.16109328+0.j        ],
        [ 0.04613419-0.36271089j,  0.04613419+0.36271089j,
         -0.0354862 +0.j        ,  0.21978944+0.j        ],
        [ 0.02768301-0.0460023j ,  0.02768301+0.0460023j ,
         -0.04250245+0.j        , -0.49462257+0.j        ],
        [ 0.4019145 +0.07950866j,  0.4019145 -0.07950866j,
          0.32119837+0.j        , -0.82528181+0.j        ]]))

## getitem et setitem
* indices
* slices
* Boolean arrays

## Saving/reading Numpy array
* ASCII (libre office)
* Binary

In [109]:
a = np.random.normal(size=(10, 4))


In [111]:
np.savetxt('my_array.txt', a)

In [112]:
np.loadtxt('my_array.txt')

array([[ 0.02868559, -1.425457  ,  1.95138126, -0.24759271],
       [ 0.33832412, -0.24478021, -1.23404395,  0.92638202],
       [-0.06830939, -0.7654846 , -0.30129999, -0.70535928],
       [-1.41336024,  0.76085657, -0.4845402 , -0.53658406],
       [ 2.44235216,  0.13122639, -0.15438534, -0.01533692],
       [ 0.14319429,  0.9917272 ,  1.54060398, -0.67324704],
       [ 1.04338338, -0.51435053, -1.89672285,  0.59178763],
       [-0.5089741 ,  0.94451801,  0.11436102, -0.38169956],
       [-0.8855514 , -0.50228262, -0.89388725,  1.31441556],
       [-2.12351071,  1.97516218,  0.45480663, -0.73979774]])

In [113]:
np.loadtxt('data.csv')

array([[1.000000e+00, 1.200000e+01],
       [2.000000e+00, 3.240000e+02],
       [2.340000e+02, 2.345643e+02],
       [3.445600e+04, 3.420000e+02]])

In [114]:
a = np.random.normal(size=(1000000))
np.savetxt('large_file.txt', a)

In [116]:
%time b = np.loadtxt('large_file.txt')

CPU times: user 1.93 s, sys: 14.2 ms, total: 1.95 s
Wall time: 1.94 s


In [118]:
np.arange(10, dtype='float64')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [119]:
a = np.random.normal(size=(1000000))
np.save('large_file.npy', a)

In [120]:
%time np.load('large_file.npy')

CPU times: user 0 ns, sys: 52.1 ms, total: 52.1 ms
Wall time: 51.9 ms


array([ 0.23914321,  0.44972072, -1.33367457, ...,  0.08092086,
       -1.78435534, -2.07406472])

## Inside numpy array
* data, shape, strides
* Broadcast

In [121]:
a = np.zeros((5, 5))
b = a[1:5, 3:5]
b[:,:] = 1
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])